export const GET_USER_DATA = 'GET_USER_DATA';
export const SIGNUP = 'SIGNUP';
export const SIGNIN = 'SIGNIN';
export const SIGNOUT = 'SIGNOUT';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const APP_BOOT = 'APP_BOOT';
export const GET_ACCOUNT_CATEGORY = 'GET_ACCOUNT_CATEGORY';
export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE';
export const AFTER_SIGN_IN_GOOGLE = 'AFTER_SIGN_IN_GOOGLE';

